---
# Template playbook for Linux System Roles
# https://linux-system-roles.github.io/
# https://galaxy.ansible.com/ui/standalone/namespaces/4114
# https://github.com/linux-system-roles/

- hosts: rhel
  become: yes
  become_method: sudo
  become_user: root
  vars:

    timesync_ntp_servers:

      - hostname: 0.rhel.pool.ntp.org
        # - hostname: {{ ntp1 }}
        iburst: yes

      - hostname: 1.rhel.pool.ntp.org
        iburst: yes

      - hostname: foo.example.org
        pool: yes
        minpoll: 6
        maxpoll: 10
        iburst: no

      - hostname: bar.example.org
        pool: no
        minpoll: 4
        maxpoll: 6
        iburst: yes

  roles:
    - rhel-system-roles.timesync
    # - linux-system-roles.timesync
